SELECT DISTINCT MFR
FROM ORDERS
INNER JOIN CUSTOMERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM
WHERE YEAR(ORDER_DATE) = 2008
AND COMPANY LIKE '%CORP%'
ORDER BY MFR ASC;

SELECT CUST_NUM, MONTH(ORDER_DATE) AS Місяць_проведення_замовлення, COUNT(DISTINCT ORDER_NUM) AS Кількість_унікальних_замовлень
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.CUST_NUM = ORDERS.CUST
WHERE YEAR(ORDER_DATE) = 2008
AND COMPANY LIKE '%CORP%'
GROUP BY CUST_NUM, MONTH(ORDER_DATE)
ORDER BY Кількість_унікальних_замовлень DESC;

SELECT DISTINCT CUST_NUM, UPPER(COMPANY) AS CompanyName, DESCRIPTION
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.CUST_NUM = ORDERS.CUST
AND YEAR(ORDER_DATE) = 2008
LEFT JOIN PRODUCTS ON ORDERS.PRODUCT = PRODUCTS.PRODUCT_ID
WHERE COMPANY LIKE '%CORP%'
GROUP BY CUST_NUM, UPPER(COMPANY), DESCRIPTION
ORDER BY CUST_NUM;
